### ISSUE TITLE
How to write efficient unit test

### ISSUE THREAD

**Issue by fsyyft** [songjiayang/songjiayang#1]
请问一下大佬，你的这个 Topic 有没有录音？

**Comment by fsyyft** [comment]
https://www.slideshare.net/songjiayang/testing-in-go-236709707

**Comment by songjiayang** [comment]
部门知识分享，暂时没有录音，不过我可以组织一次线上分享，另外分享的所有代码可以参考 https://github.com/songjiayang/gotesting

**Comment by fsyyft** [comment]
非常棒，什么时候分享，在线等。
